
name: 'StandardRB Action'
description: 'A GitHub Action that lints your Ruby code with StandardRB!'
author: 'Andrew Mason <andrewmcodes@protonmail.com>'
inputs:
  ruby-version: 
    description: 'Ruby version'
    required: true
    default: '3.2.2'

runs:
  using: composite
  steps:
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ inputs.ruby-version }}
        bundler-cache: true
    - name: Run standardrb
      shell: bash
      run: bundle exec standardrb --parallel -f github
env:
  GITHUB_TOKEN: secrets.GITHUB_TOKEN
branding:
  icon: 'code'
  color: 'gray-dark'
