name: Changelog

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby 3.1
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.2
    - name: Create local changes
      run: |
        gem install bundler
        bundle install
        github_changelog_generator -u andrewmcodes -p standardrb-action --token ${{ secrets.GITHUB_TOKEN }}
    - name: Commit files
      run: |
        git config --local user.email "andrewmcodes@protonmail.com"
        git config --local user.name "Andrew Mason"
        git commit -m "Update changelog" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
